services:
  api:
    build: .
    ports:
      - "8000:80"
    restart: unless-stopped
 
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped
 
 